In [ ]:
import PySimpleGUI as sg
import time

sg.SetOptions(margins=(0,0), element_padding=(0,0))

layout = [[sg.Graph(canvas_size=(400,400), graph_bottom_left=(-400,-400), graph_top_right=(400, 400), background_color='red', key='graph')],]

window = sg.Window('Zoom', layout, background_color='red', transparent_color='red', no_titlebar=True, alpha_channel=.5, grab_anywhere=True).Finalize()

graph = window.FindElement('graph')
circle = graph.DrawCircle((0,0), 150, fill_color='green',line_color='green')

time.sleep(5)
# while True:
#     event, values = window.Read()
#     if event is None:
#         break

In [ ]:
import PySimpleGUI as sg
import time

sg.SetOptions(margins=(0,0), element_padding=(0,0))

layout = [[sg.Graph(canvas_size=(400,400), graph_bottom_left=(-400,-400), graph_top_right=(400, 400), background_color='red', key='graph')],]

window = sg.Window('Zoom', layout, background_color='red', transparent_color='red', no_titlebar=True, alpha_channel=.5, grab_anywhere=True).Finalize()

In [ ]:
window['graph'].DrawCircle((0,0), 150, fill_color='green',line_color='green')


In [ ]:
window.close()

In [1]:
from screeninfo import get_monitors
for m in get_monitors():
    print(str(m))

Monitor(x=0, y=0, width=1680, height=1050, width_mm=474, height_mm=296, name='\\\\.\\DISPLAY1', is_primary=True)


In [ ]:
pip install screeninfo

In [2]:
import ctypes
user32 = ctypes.windll.user32
screensize = user32.GetSystemMetrics(78), user32.GetSystemMetrics(79)

In [4]:
screensize[0]

1680

In [5]:
import numpy as np
base=np.load("calibracion\\Calibracion_Vectores_xy_teclado_mouse.npy",allow_pickle=True)
base

array([{'pts3d': array([[ 6.10904842e-02, -2.30324937e-01,  1.05384441e+00],
              [ 4.87950047e-02, -2.40192874e-01,  1.05506871e+00],
              [ 3.32730791e-02, -2.45724076e-01,  1.05735521e+00],
              [ 2.06098650e-02, -2.48699543e-01,  1.05904064e+00],
              [ 1.12241577e-02, -2.50164230e-01,  1.06005214e+00],
              [ 3.08805969e-02, -2.43490208e-01,  1.04933925e+00],
              [ 1.51676426e-02, -2.44157424e-01,  1.04788966e+00],
              [ 5.86760938e-03, -2.43411492e-01,  1.04713856e+00],
              [-6.96585841e-04, -2.42275260e-01,  1.04621748e+00],
              [ 3.23103507e-02, -2.38288994e-01,  1.04837063e+00],
              [ 1.47143170e-02, -2.38803550e-01,  1.04553465e+00],
              [ 3.38197941e-03, -2.38394622e-01,  1.04428282e+00],
              [-5.16579010e-03, -2.37840709e-01,  1.04295811e+00],
              [ 3.51620272e-02, -2.31351895e-01,  1.04775266e+00],
              [ 1.72262790e-02, -2.31764753e-01,  1.

In [3]:
a=[1,2,3]
b=[4,5,6]
aa=np.array([a])
bb=np.concatenate((aa, [b]), axis=0)
bb

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
bb[0]

array([1, 2, 3])

In [5]:
base[0]['pts3d']

array([[-0.32290576, -0.20518443,  1.23307894],
       [-0.34947072, -0.22041309,  1.23901079],
       [-0.36497712, -0.22222635,  1.23695848],
       [-0.37620916, -0.21940687,  1.23472749],
       [-0.3847066 , -0.21527221,  1.23312205],
       [-0.38546794, -0.21804834,  1.23188669],
       [-0.40189529, -0.21149807,  1.2285865 ],
       [-0.40898078, -0.2061428 ,  1.22815051],
       [-0.41288098, -0.20286094,  1.22881616],
       [-0.38009326, -0.20617269,  1.22682192],
       [-0.4010378 , -0.19741124,  1.22081454],
       [-0.40964841, -0.19122127,  1.21848679],
       [-0.41696896, -0.18694569,  1.21692434],
       [-0.37081317, -0.19358265,  1.22205734],
       [-0.39038264, -0.18629972,  1.21639249],
       [-0.40150114, -0.18092967,  1.21400036],
       [-0.40870729, -0.17733442,  1.21161255],
       [-0.36087123, -0.18214359,  1.22013475],
       [-0.37612598, -0.17463036,  1.21456155],
       [-0.38621106, -0.17128343,  1.21213474],
       [-0.39562575, -0.16855641,  1.210

In [ ]:
import plotly.graph_objects as go
class Canvas_(FigureCanvas):
    def __init__(self,DataProcess):
        #self.parent=parent
        self.DataProcess=DataProcess
    def draw_(self):

        try:
        
#        self.fig,self.ax=plt.subplots(1,dpi=100,figsize=(5,5),sharey=True,facecolor='white')
            self.fig=go.Figure(data=[go.Scatter3d(x=self.DataProcess['cube_points'][:][0][0],y=self.DataProcess['cube_points'][:][1][0],z=self.DataProcess['cube_points'][:][2][0],
            mode='markers',marker=dict(size=5,color='red',opacity=0.5))])
            super().__init__(self.fig)
            #self.setParent(self.parent)

        # nombres=['15','2','3','4','5']
        # colores=['red','blue','red','orange','green']
        # tamaño=[10,15,20,25,30]
        # self.ax.bar(nombres,tamaño,color=colores)
        # self.fig.suptitle('Grafica',size=9)

        
            self.fig.update_layout(autosize=False,width=900,height=900)
            self.fig.show()
        except:
            print("error draw()")
            pass

In [6]:
pip install PyQtWebEngine

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
     ------------------------------------- 181.1/181.1 KB 11.4 MB/s eta 0:00:00
     --------------------------------------- 60.0/60.0 MB 43.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.
